names:
  # 兵种 主世界
  Barbarian: 野蛮人
  Archer: 弓箭手
  Giant: 巨人
  Goblin: 哥布林
  Wall Breaker: 炸弹人
  Balloon: 气球兵
  Wizard: 法师
  Healer: 天使
  Dragon: 飞龙
  P.E.K.K.A: 皮卡超人
  Baby Dragon: 飞龙宝宝
  Miner: 掘地矿工
  Electro Dragon: 雷电飞龙
  Yeti: 大雪怪
  Dragon Rider: 龙骑士
  Electro Titan: 雷电泰坦
  Root Rider: 根蔓骑士
  Apprentice Warden: 见习守护者
  Druid: 德鲁伊
  Minion: 亡灵
  Hog Rider: 野猪骑士
  Valkyrie: 瓦基丽武神
  Golem: 戈仑石人
  Witch: 女巫
  Lava Hound: 熔岩猎犬
  Bowler: 巨石投手
  Ice Golem: 冰人
  Headhunter: 猎手
  Super Barbarian: 超级野蛮人
  Super Archer: 超级弓箭手
  Super Giant: 超级巨人
  Sneaky Goblin: 隐秘哥布林
  Super Wall Breaker: 超级炸弹人
  Rocket Balloon: 火箭气球兵
  Super Wizard: 超级法师
  Super Dragon: 超级飞龙
  Inferno Dragon: 地狱飞龙
  Super Minion: 超级亡灵
  Super Valkyrie: 超级瓦基丽武神
  Super Witch: 超级女巫
  Ice Hound: 寒冰猎犬
  Super Bowler: 超级巨石投手
  Super Hog Rider: 超级野猪骑士
  # 攻城器
  Wall Wrecker: 攻城车
  Battle Blimp: 攻城飞艇
  Stone Slammer: 攻城气球
  Siege Barracks: 攻城训练营
  Log Launcher: 攻城滚木车
  Flame Flinger: 烈焰投石车
  Battle Drill: 攻城钻机
  # 英雄
  Barbarian King: 野蛮人之王
  Archer Queen: 弓箭女皇
  Grand Warden: 大守护者
  Royal Champion: 飞盾战神
  Minion Prince: 亡灵王子
  Dragon Duke: 龙王
  Battle Machine: 战争机器
  Battle Copter: 战斗直升机
  # 法术
  Lightning Spell: 雷电法术
  Healing Spell: 治疗法术
  Rage Spell: 狂暴法术
  Jump Spell: 弹跳法术
  Freeze Spell: 冰冻法术
  Clone Spell: 克隆法术
  Invisibility Spell: 隐形法术
  Recall Spell: 召回法术
  Poison Spell: 毒药法术
  Earthquake Spell: 地震法术
  Haste Spell: 急速法术
  Skeleton Spell: 骷髅法术
  Bat Spell: 蝙蝠法术
  Overgrowth Spell: 蔓生法术
  Revive Spell: 复活法术
  Ice Block Spell: 冰障法术
  Totem Spell: 图腾法术
  # 夜世界
  Raged Barbarian: 夜世界野蛮人
  Electrofire Wizard: 电火法师
  Sneaky Archer: 隐秘弓箭手
  Beta Minion: 夜世界亡灵
  Night Witch: 夜女巫
  Boxer Giant: 巨人拳击手
  Bomber: 炸弹人
  Power P.E.K.K.A: 夜世界皮卡
  Cannon Cart: 炮车
  # 都城
  Hog Glider: 野猪飞骑
  Super Miner: 超级矿工
  Drop Ship: 骷髅气球
  # 宠物
  L.A.S.S.I: fw
  Mighty Yak: 牛牛
  Electro Owl: 电枭
  Unicorn: 独角兽
  Phoenix: 凤凰
  Poison Lizard: 毒蜥
  Diggy: 挖挖
  Frosty: 冰牙
  Spirit Fox: 灵狐
  Angry Jelly: 水母
  # 蛮王
  Barbarian Puppet: 野蛮人玩偶
  Rage Vial: 狂暴药水瓶
  Earthquake Boots: 地震靴
  Giant Gauntlet: 巨型手套
  Vampstache: 治疗胡须
  Stick Horse: 木棍马驹
  # 女王
  Archer Puppet: 弓箭手玩偶
  Invisibility Vial: 隐形药水瓶
  Giant Arrow: 擎天巨矢
  Healer Puppet: 天使玩偶
  Frozen Arrow: 冰冻箭
  Action Figure: 动作玩偶
  # 永王
  Eternal Tome: 永恒书卷
  Life Gem: 生命宝石
  Rage Gem: 狂暴宝石
  Healing Tome: 治疗书卷
  Fireball: 火球
  # 闰土
  Royal Gem: 皇家宝石
  Seeking Shield: 追踪盾牌
  Hog Rider Puppet: 野猪骑士玩偶
  Haste Vial: 急速药水瓶
  Rocket Spear: 火箭长矛
  Frost Flake: 冰晶
  Electro Boots: 雷电战靴
  # 亡灵王子
  Dark Orb: 暗黑魔球
  Metal Pants: 金属裤头
  Noble Iron: 贵族哑铃
  Henchmen Puppet: 王子护卫玩偶
  Dark Crown: 暗黑王冠
  # 龙王
  Stun Blaster: 震爆器
  Flame Blower: 助燃器
  Fire Heart: 龙心
  Revenge Deck: 反击卡组
